name: mtw

services:
  # MTW server + worker
  server:
    build:
      context: .
    # image: my_repository/mtw-server:latest  # if the image is uploaded to a repository, uncomment
    init: true  # Use tini to handle messages
    # TODO: move to entrypoint.sh
    # TODO: listen to container's ip rather than listening on all interface (0.0.0.0)
    command: > 
            bash -c "python /app/set-mtw-admin.py --login $${ADMIN_LOGIN} --pwd $$(cat /run/secrets/admin-settings)
            && python mtw-server.py --host 0.0.0.0 $${DEBUG} & python mtw-worker.py $${DEBUG}"
    depends_on:
      jena_fuseki:
        condition: service_started
    volumes:
      # Volumes
      - mtw-data:/app/instance/
    ports:
      - 55930:55930
    secrets:
      - admin-settings
    environment:
      # - DEBUG=--debug
      - ADMIN_LOGIN=admin

  # Jena Fuseki SPARQL server
  jena_fuseki:
    image: stain/jena-fuseki:latest
    entrypoint: ["/sbin/tini", "--"]
    # TODO: move to entrypoint.sh
    command: >
            bash -c "export ADMIN_PASSWORD=$$(cat /run/secrets/admin-settings) 
            && source /docker-entrypoint.sh /jena-fuseki/fuseki-server $${DEBUG}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped
    volumes:
      # Volumes
      - fuseki-data:/fuseki
    ports:
      - 3030:3030
    secrets:
      - admin-settings
    environment:
      # - DEBUG=--debug
      # TODO: Find optimal setting for RAM value (4G ?)
      - JVM_ARGS=-Xmx2G
      - TDB=2

  # Service to load the mesh into the triple-store in jena_fuseki
  staging:
    extends: jena_fuseki
    profiles: ["staging"]
    entrypoint: ""
    command: >
            bash -c "mkdir -p /fuseki/configuration/ 
            && cp /fuseki-tmp/mesh.ttl /fuseki/configuration/mesh.ttl
            && read -p 'All the data in the current mesh will be lost. Are you sure (y/N) ? ' -n 1 -r REPLY
            && echo ""
            && if [[ $$REPLY =~ ^[Yy]$ ]]; 
            then
              /jena-fuseki/tdbloader2 --loc /fuseki/databases/mesh /staging/mesh.nt.gz;
              /jena-fuseki/tdbloader2 --loc /fuseki/databases/mesh /staging/mesh-trx-*.nt.gz;
              cd /fuseki;
              java -cp /jena-fuseki/fuseki-server.jar jena.textindexer --desc=/fuseki/configuration/mesh.ttl;
            else
              echo "Abort..."
            fi"
    
    volumes:
      # Binds
      - ./mesh.ttl:/fuseki-tmp/mesh.ttl
      - ./mesh-data/:/staging/:ro

      # Volumes
      - fuseki-data:/fuseki

volumes:
  mtw-data:
  fuseki-data:

secrets:
  admin-settings:
    file: ./admin_settings.txt