name: mtw

services:
  # MTW server + worker
  server:
    build:
      context: .
    init: true  # Use tini to handle messages
    # TODO: move to entrypoint.sh
    # TODO: listen to container's ip rather than listening on all interface (0.0.0.0)
    command: > 
            bash -c "python /app/set-mtw-admin.py --login $${ADMIN_LOGIN} --pwd $$(cat /run/secrets/admin-settings)
            && python mtw-server.py --host 0.0.0.0 $${DEBUG} & python mtw-worker.py $${DEBUG}"
    depends_on:
      - jena_fuseki
    volumes:
      # Volumes
      - mtw-data:/app/instance/
    ports:
      - 55930:55930
    secrets:
      - admin-settings
    environment:
      - DEBUG=--debug
      - ADMIN_LOGIN=admin
    labels:
      # The domain the service will respond to
      - "traefik.http.routers.server.rule=Host(`mtw.localhost`)"
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.server.entrypoints=web"

  # Jena Fuseki SPARQL server
  jena_fuseki:
    image: stain/jena-fuseki:latest
    entrypoint: ["/sbin/tini", "--"]
    # TODO: move to entrypoint.sh
    command: >
            bash -c "export ADMIN_PASSWORD=$$(cat /run/secrets/admin-settings) 
            && source /docker-entrypoint.sh /jena-fuseki/fuseki-server --debug"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    volumes:
      # Volumes
      - fuseki-data:/fuseki
    ports:
      - 3030:3030
    secrets:
      - admin-settings
    environment:
      # TODO: Find optimal setting for RAM value (4G ?)
      - JVM_ARGS=-Xmx2G
      - TDB=2
    labels:
      # The domain the service will respond to
      - "traefik.http.routers.jena_fuseki.rule=Host(`fuseki.localhost`)"
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.jena_fuseki.entrypoints=web"

  # Service to load the mesh into the triple-store in jena_fuseki
  staging:
    extends: jena_fuseki
    profiles: ["staging"]
    entrypoint: ""
    command: >
            bash -c "mkdir -p /fuseki/configuration/ 
            && cp /fuseki-tmp/mesh.ttl /fuseki/configuration/mesh.ttl
            && read -p 'All the data in the current mesh will be lost. Are you sure (y/N) ? ' -n 1 -r REPLY
            && echo ""
            && if [[ $$REPLY =~ ^[Yy]$ ]]; 
            then
              /jena-fuseki/tdbloader2 --loc /fuseki/databases/mesh /staging/mesh.nt.gz;
              /jena-fuseki/tdbloader2 --loc /fuseki/databases/mesh /staging/mesh-trx-*.nt.gz;
              cd /fuseki;
              java -cp /jena-fuseki/fuseki-server.jar jena.textindexer --desc=/fuseki/configuration/mesh.ttl;
            else
              echo "Abort..."
            fi"
    
    volumes:
      # Binds
      - ./mesh.ttl:/fuseki-tmp/mesh.ttl
      - ./mesh-data/:/staging/:ro

      # Volumes
      - fuseki-data:/fuseki

  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.0
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      # Enabling Docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entryPoints.web.address=:80"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mtw-data:
  fuseki-data:
  staging:

secrets:
  admin-settings:
    file: ./admin_settings.txt